<?php

namespace Vbv\WebaliasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AliasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AliasRepository extends EntityRepository
{
	public function getAliases($tag, $code=null)
	{
		if($code != null)
		{
			return $this->findBy(
	    		array('tag' => $tag, 'code' => $code)
			);
		}
		else
		{
			return $this->findBy(
	    		array('tag' => $tag)
			);
		}
	}
}